export const productReviews = [
  {
    id: 1,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69525.png",
    productName: "EGIE Wireless Controller",
    username: "Sarah Lee",
    rating: 4,
    review: "Great controller, works perfectly with my PC and PS5!",
    date: "Mar 15, 2024",
    time: "14:30",
  },
  {
    id: 2,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69526.png",
    productName: "EGIE Pro Gamepad",
    username: "John Smith",
    rating: 3,
    review: "Good value for the price, but the battery life could be better.",
    date: "Feb 28, 2024",
    time: "09:15",
  },
  {
    id: 3,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69527.png",
    productName: "EGIE Turbo Joystick",
    username: "Priya Patel",
    rating: 5,
    review: "Absolutely love it! Fast shipping and great packaging.",
    date: "Jan 10, 2024",
    time: "16:45",
  },
  {
    id: 4,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69528.png",
    productName: "EGIE Classic Pad",
    username: "Carlos Rivera",
    rating: 2,
    review: "Had some issues connecting to Bluetooth, but customer service helped.",
    date: "Dec 22, 2023",
    time: "11:20",
  },
  {
    id: 5,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69529.png",
    productName: "EGIE Elite Controller",
    username: "Anna Müller",
    rating: 5,
    review: "Best purchase this year! Highly recommend to gamers.",
    date: "Nov 5, 2023",
    time: "13:00",
  },
  {
    id: 6,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69525.png",
    productName: "EGIE Wireless Controller",
    username: "Michael Chen",
    rating: 4,
    review: "Comfortable grip and responsive buttons. Worth every penny!",
    date: "Mar 20, 2024",
    time: "10:30",
  },
  {
    id: 7,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69526.png",
    productName: "EGIE Pro Gamepad",
    username: "Emily Johnson",
    rating: 5,
    review: "Perfect for competitive gaming. No lag at all!",
    date: "Mar 18, 2024",
    time: "08:45",
  },
  {
    id: 8,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69527.png",
    productName: "EGIE Turbo Joystick",
    username: "David Martinez",
    rating: 3,
    review: "Decent product but the turbo feature is not as advertised.",
    date: "Mar 15, 2024",
    time: "15:20",
  },
  {
    id: 9,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69528.png",
    productName: "EGIE Classic Pad",
    username: "Sophie Brown",
    rating: 4,
    review: "Nostalgic design with modern features. Love it!",
    date: "Mar 12, 2024",
    time: "12:10",
  },
  {
    id: 10,
    productImg: "https://cdn-icons-png.flaticon.com/512/69/69529.png",
    productName: "EGIE Elite Controller",
    username: "James Wilson",
    rating: 5,
    review: "Premium quality and amazing customization options.",
    date: "Mar 10, 2024",
    time: "17:30",
  },
];

export const customerInquiries = [
  {
    id: 1,
    customerName: "Michael Chen",
    email: "michael.chen@email.com",
    productName: "EGIE Wireless Controller",
    question: "Does this controller support Nintendo Switch?",
    date: "Mar 20, 2024",
    time: "14:25",
    status: "Question",
    reply: null,
  },
  {
    id: 2,
    customerName: "Emily Johnson",
    email: "emily.j@email.com",
    productName: "EGIE Pro Gamepad",
    question: "What is the warranty period for this product?",
    date: "Mar 18, 2024",
    time: "09:40",
    status: "Replied",
    reply: "Thank you for your inquiry. This product comes with a 1-year warranty covering manufacturing defects.",
    repliedDate: "Mar 19, 2024",
    repliedTime: "10:15",
  },
  {
    id: 3,
    customerName: "David Martinez",
    email: "david.m@email.com",
    productName: "EGIE Turbo Joystick",
    question: "Is this compatible with Xbox Series X?",
    date: "Mar 15, 2024",
    time: "16:50",
    status: "Question",
    reply: null,
  },
  {
    id: 4,
    customerName: "Sophie Brown",
    email: "sophie.brown@email.com",
    productName: "EGIE Elite Controller",
    question: "Can I customize the button mapping on this controller?",
    date: "Mar 12, 2024",
    time: "11:30",
    status: "Replied",
    reply: "Yes! Our Elite Controller supports full button remapping through our companion app available on iOS and Android.",
    repliedDate: "Mar 13, 2024",
    repliedTime: "14:20",
  },
];

export const REVIEWS_PER_PAGE = 40;
export const INQUIRIES_PER_PAGE = 20;