// Mock activity log data - Replace with actual API call
export const activityLogs = [
  {
    id: 1,
    timestamp: "2025-06-15 14:45:23",
    user: "mikko2@gmail.com",
    userType: "Admin",
    userRole: "Administrator",
    action: "Updated Product",
    module: "Products",
    details: 'Changed price of "Gaming Mouse Pro" from ₱1,499 to ₱1,299',
    severity: "Normal",
    outcome: "Success",
    previousValue: "₱1,499",
    newValue: "₱1,299",
    ipAddress: "192.168.1.105",
    location: "Manila, Philippines",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    metadata: {
      productId: "PRD-001",
      category: "Gaming Accessories",
      affectedRecords: "1",
    },
  },
  {
    id: 2,
    timestamp: "2025-06-15 14:45:12",
    user: "mikko2@gmail.com",
    userType: "Admin",
    userRole: "Order Manager",
    action: "Accepted Order",
    module: "Orders",
    details: "Accepted Order #ORD-12345 from John Doe",
    severity: "Normal",
    outcome: "Success",
    ipAddress: "192.168.1.105",
    location: "Manila, Philippines",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
    metadata: {
      orderId: "ORD-12345",
      customerName: "John Doe",
      orderAmount: "₱15,499",
    },
  },
  {
    id: 3,
    timestamp: "2025-06-15 14:40:58",
    user: "geooc@gmail.com",
    userType: "Admin",
    userRole: "Product Manager",
    action: "Created Product",
    module: "Products",
    details: 'Created new product "Mechanical Keyboard RGB"',
    severity: "Low",
    outcome: "Success",
    ipAddress: "192.168.1.110",
    location: "Quezon City, Philippines",
    userAgent: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7)",
    metadata: {
      productId: "PRD-002",
      category: "Keyboards & Mice",
      price: "₱5,499",
    },
  },
  {
    id: 4,
    timestamp: "2025-06-15 14:38:42",
    user: "tuplon@gmail.com",
    userType: "Admin",
    userRole: "Marketing Manager",
    action: "Created Voucher",
    module: "Promotions",
    details: 'Created voucher "SUMMER25" with 25% discount',
    severity: "Normal",
    outcome: "Success",
    ipAddress: "192.168.1.115",
    location: "Makati, Philippines",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    metadata: {
      voucherCode: "SUMMER25",
      discountType: "Percentage",
      discountValue: "25%",
      validUntil: "2025-09-30",
    },
  },
  {
    id: 5,
    timestamp: "2025-06-15 14:35:19",
    user: "MokiM@gmail.com",
    userType: "Admin",
    userRole: "Customer Support",
    action: "Replied an Inquirie",
    module: "Feedback",
    details: "Replied to customer inquiry #INQ-789 about shipping",
    severity: "Low",
    outcome: "Success",
    ipAddress: "192.168.1.120",
    location: "Pasig, Philippines",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    metadata: {
      inquiryId: "INQ-789",
      customerEmail: "customer@example.com",
      responseTime: "15 minutes",
    },
  },
  {
    id: 6,
    timestamp: "2025-06-15 14:30:05",
    user: "bouts@gmail.com",
    userType: "Admin",
    userRole: "Shipping Manager",
    action: "Shipped an order",
    module: "Shipping",
    details: "Shipped order #ORD-12340 via LBC Express",
    severity: "Normal",
    outcome: "Success",
    ipAddress: "192.168.1.125",
    location: "Taguig, Philippines",
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X)",
    metadata: {
      orderId: "ORD-12340",
      trackingNumber: "LBC123456789",
      courier: "LBC Express",
      estimatedDelivery: "2025-06-18",
    },
  },
  {
    id: 7,
    timestamp: "2025-06-15 14:25:37",
    user: "Muyna@gmail.com",
    userType: "Admin",
    userRole: "Order Manager",
    action: "Accepted Order",
    module: "Orders",
    details: "Accepted Order #ORD-12341 from Jane Smith",
    severity: "Normal",
    outcome: "Success",
    ipAddress: "192.168.1.130",
    location: "Cebu City, Philippines",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    metadata: {
      orderId: "ORD-12341",
      customerName: "Jane Smith",
      orderAmount: "₱8,999",
    },
  },
  {
    id: 8,
    timestamp: "2025-06-15 09:15:22",
    user: "customer_john@example.com",
    userType: "Customer",
    userRole: "Registered User",
    action: "Account Created",
    module: "Customers",
    details: "New customer account registered",
    severity: "Low",
    outcome: "Success",
    ipAddress: "203.177.45.123",
    location: "Manila, Philippines",
    userAgent: "Mozilla/5.0 (iPhone; CPU iPhone OS 16_0 like Mac OS X)",
    metadata: {
      customerId: "CUST-1001",
      registrationMethod: "Email",
      emailVerified: "Yes",
    },
  },
  {
    id: 9,
    timestamp: "2025-06-15 08:45:11",
    user: "admin@egie.com",
    userType: "Admin",
    userRole: "Super Admin",
    action: "Delete Product",
    module: "Products",
    details: 'Deleted discontinued product "Old Mouse Model"',
    severity: "High",
    outcome: "Success",
    previousValue: "Product ID: PRD-OLD-001",
    newValue: "Deleted",
    ipAddress: "192.168.1.100",
    location: "Manila, Philippines",
    userAgent: "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
    metadata: {
      productId: "PRD-OLD-001",
      reason: "Discontinued",
      deletedBy: "Super Admin",
    },
  },
  {
    id: 10,
    timestamp: "2025-06-15 07:30:45",
    user: "suspicious_user@test.com",
    userType: "Customer",
    userRole: "Guest",
    action: "Failed Login Attempt",
    module: "Security",
    details: "Multiple failed login attempts detected",
    severity: "Critical",
    outcome: "Failure",
    ipAddress: "45.123.67.89",
    location: "Unknown Location",
    userAgent: "Unknown User Agent",
    metadata: {
      attempts: "5",
      accountLocked: "Yes",
      securityAlert: "High Risk IP",
    },
  },
];

export const LOGS_PER_PAGE = 10;