export const discounts = [
  {
    id: 1,
    name: "Summer Sale",
    type: "percent",
    value: 20,
    dates: "06/01/25 - 06/30/25",
    used: 145,
    appliesTo: "All Products",
    minSpend: 500,
    userEligibility: "All Users",
  },
  {
    id: 2,
    name: "Flash Discount",
    type: "fixed",
    value: 100,
    dates: "05/15/25 - 05/20/25",
    used: 89,
    appliesTo: "Controllers",
    minSpend: 1000,
    userEligibility: "New Users",
  },
  {
    id: 3,
    name: "Member Exclusive",
    type: "percent",
    value: 15,
    dates: "01/01/25 - 12/31/25",
    used: 320,
    appliesTo: "Gaming Accessories",
    minSpend: null,
    userEligibility: "Existing Users",
  },
  {
    id: 4,
    name: "Bundle Deal",
    type: "fixed",
    value: 250,
    dates: "07/01/25 - 07/15/25",
    used: 56,
    appliesTo: "Console Bundles",
    minSpend: 5000,
    userEligibility: "Selected",
  },
  {
    id: 5,
    name: "Black Friday",
    type: "percent",
    value: 30,
    dates: "11/24/25 - 11/26/25",
    used: 512,
    appliesTo: "All Products",
    minSpend: null,
    userEligibility: "All Users",
  },
];